package com.arno.robotica.automation.client;

import com.arno.robotica.Robotica;
import com.arno.robotica.automation.block.FarmBotBlock;
import com.arno.robotica.automation.entity.FarmBotBlockEntity;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.block.model.BakedQuad;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.core.Direction;
import net.minecraft.core.Vec3i;
import net.minecraft.util.Mth;
import net.minecraft.util.RandomSource;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.AABB;
import net.neoforged.neoforge.client.event.ModelEvent;
import org.joml.Quaternionf;
import org.joml.Vector3f;

import java.util.ArrayList;
import java.util.List;

/**
 * Stumpy's and Sprout's arms, drawn apart from the block model so they can swing: a short wind-up and slash on every
 * action (timed by the bot's block event), resting pose otherwise. Faces are shaded like chunk geometry, so the arms
 * match the body. Also draws the work area outline.
 */
public class FarmBotRenderer<T extends FarmBotBlockEntity> extends AreaOutlineRenderer<T> {
    /** Arm part models, generated by scripts/data/automation_data.py. */
    private static final ModelResourceLocation SAW_ARM = part("stumpy_saw_arm");
    private static final ModelResourceLocation SAW_BLADE = part("stumpy_saw_blade");
    private static final ModelResourceLocation AXE_ARM = part("stumpy_axe_arm");
    private static final ModelResourceLocation SCYTHE_ARM = part("sprout_scythe_arm");
    private static final ModelResourceLocation POUCH_ARM = part("sprout_pouch_arm");

    // Pivots in block units (model px / 16): the shoulder centres and the saw hub.
    private static final float RIGHT_X = 12.7F / 16, LEFT_X = 3.3F / 16, SHOULDER_Y = 7.25F / 16, SHOULDER_Z = 0.5F;
    private static final float BLADE_X = 14.7F / 16, BLADE_Y = 6.5F / 16;

    private static final float[] FULL = {1.0F, 1.0F, 1.0F, 1.0F};
    private static final RandomSource RANDOM = RandomSource.create();

    private final boolean stumpy;
    private final Part right;
    private final Part left;
    private final Part blade;
    private final Quaternionf rotation = new Quaternionf();
    private final Vector3f normal = new Vector3f();
    private final int[] lights = new int[4];

    public FarmBotRenderer(boolean stumpy) {
        this.stumpy = stumpy;
        this.right = new Part(stumpy ? SAW_ARM : SCYTHE_ARM);
        this.left = new Part(stumpy ? AXE_ARM : POUCH_ARM);
        this.blade = stumpy ? new Part(SAW_BLADE) : null;
    }

    private static ModelResourceLocation part(String name) {
        return ModelResourceLocation.standalone(Robotica.id("block/" + name));
    }

    public static void registerModels(ModelEvent.RegisterAdditional event) {
        for (ModelResourceLocation id : List.of(SAW_ARM, SAW_BLADE, AXE_ARM, SCYTHE_ARM, POUCH_ARM)) event.register(id);
    }

    @Override
    public void render(T be, float partialTick, PoseStack pose, MultiBufferSource buffers, int light, int overlay) {
        super.render(be, partialTick, pose, buffers, light, overlay);
        BlockState state = be.getBlockState();
        if (!(be.getLevel() instanceof ClientLevel level) || !state.hasProperty(FarmBotBlock.FACING)) return;
        float t = be.swingTime(partialTick);
        float rightAngle = 0, leftAngle = 0, spin = 0;
        if (t >= 0) {
            if (stumpy) {
                rightAngle = swing(t, 12, -25);
                leftAngle = swing(t, 40, -75);
                spin = -540.0F * ease(t / FarmBotBlockEntity.SWING_TICKS);
            } else {
                switch (be.swingKind()) {
                    case 1 -> { // plant: the pouch tips forward
                        rightAngle = swing(t, 5, -10);
                        leftAngle = swing(t, 20, -55);
                    }
                    case 2 -> { // till: a hard chop
                        rightAngle = swing(t, 40, -85);
                        leftAngle = swing(t, -8, 12);
                    }
                    default -> { // harvest
                        rightAngle = swing(t, 30, -70);
                        leftAngle = swing(t, -8, 12);
                    }
                }
            }
        }
        Direction facing = state.getValue(FarmBotBlock.FACING);
        VertexConsumer vc = buffers.getBuffer(RenderType.cutout());
        lights[0] = lights[1] = lights[2] = lights[3] = light;
        pose.pushPose();
        if (facing != Direction.NORTH) {
            pose.rotateAround(rotation.rotationY((180.0F - facing.toYRot()) * Mth.DEG_TO_RAD), 0.5F, 0, 0.5F);
        }
        pose.pushPose();
        pitch(pose, rightAngle, RIGHT_X);
        draw(level, pose, vc, right);
        if (blade != null) {
            if (spin != 0) pose.rotateAround(rotation.rotationX(spin * Mth.DEG_TO_RAD), BLADE_X, BLADE_Y, SHOULDER_Z);
            draw(level, pose, vc, blade);
        }
        pose.popPose();
        pitch(pose, leftAngle, LEFT_X);
        draw(level, pose, vc, left);
        pose.popPose();
    }

    /** Pitches an arm around its shoulder; positive swings the top back, negative forward (the bot faces -Z). */
    private void pitch(PoseStack pose, float degrees, float shoulderX) {
        if (degrees != 0) pose.rotateAround(rotation.rotationX(degrees * Mth.DEG_TO_RAD), shoulderX, SHOULDER_Y, SHOULDER_Z);
    }

    /** Wind-up to {@code wind} degrees, slash through to {@code slash} as it hits, then ease back to rest. */
    private static float swing(float t, float wind, float slash) {
        float hit = FarmBotBlockEntity.HIT_TICK;
        float slashTicks = 1.5F;
        if (t < hit) return wind * ease(t / hit);
        if (t < hit + slashTicks) return Mth.lerp(ease((t - hit) / slashTicks), wind, slash);
        return slash * (1.0F - ease((t - hit - slashTicks) / (FarmBotBlockEntity.SWING_TICKS - hit - slashTicks)));
    }

    private static float ease(float x) {
        x = Mth.clamp(x, 0.0F, 1.0F);
        return x * x * (3.0F - 2.0F * x);
    }

    /** Emits the part's quads with the shade a chunk would give a face pointing that way. */
    private void draw(ClientLevel level, PoseStack pose, VertexConsumer vc, Part part) {
        PoseStack.Pose last = pose.last();
        for (BakedQuad quad : part.quads()) {
            Vec3i n = quad.getDirection().getNormal();
            last.transformNormal(n.getX(), n.getY(), n.getZ(), normal);
            float shade = level.getShade(normal.x(), normal.y(), normal.z(), quad.isShade());
            vc.putBulkData(last, quad, FULL, shade, shade, shade, 1.0F, lights, OverlayTexture.NO_OVERLAY, false);
        }
    }

    @Override
    public AABB getRenderBoundingBox(T be) {
        return super.getRenderBoundingBox(be).inflate(0.5);
    }

    /** One arm model and its quads, refreshed when the models are reloaded. */
    private static final class Part {
        private final ModelResourceLocation id;
        private BakedModel model;
        private List<BakedQuad> quads = List.of();

        Part(ModelResourceLocation id) {
            this.id = id;
        }

        List<BakedQuad> quads() {
            BakedModel current = Minecraft.getInstance().getModelManager().getModel(id);
            if (current != model) {
                model = current;
                List<BakedQuad> all = new ArrayList<>();
                for (Direction dir : Direction.values()) all.addAll(current.getQuads(null, dir, RANDOM));
                all.addAll(current.getQuads(null, null, RANDOM));
                quads = all;
            }
            return quads;
        }
    }
}
